development:
  adapter: redis
  url: redis://localhost:6379/
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL", ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" }) %>
  channel_prefix: CabinAR_production
